name: Test Local Server

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start simple HTTP server in background
        run: |
          nohup python3 -m http.server 8080 &
          sleep 3

      - name: Test server with curl
        run: |
          curl -v http://localhost:8080

      - name: Install proxy.py
        run: |
          python3 -m pip install --upgrade pip
          pip install proxy.py

      - name: Start proxy.py forward proxy
        run: |
          nohup python3 -m proxy --hostname 127.0.0.1 --port 8080 &
          sleep 3

      - name: Test proxy with curl
        run: |
          curl -v --proxy http://127.0.0.1:8080 http://google.com
